### PR TITLE
Create indicator: Chenlun Phishing Kit 88426540

### PR DESCRIPTION
**Pull request by masaomi346**
**Creating IOK for Rakuten Phishing targeting Japanese users.**

Description:
Detects a Rakuten phishing kit targeting Japanese users.

References:
https://urlscan.io/result/88426540-8f66-4fe2-b8f2-526e7025ace7
https://urlscan.io/result/ab83507a-012d-413e-bd3f-fee0fe5e9da4

Tags:
`target.rakuten`,`target_country.japan`

Screenshot:
88426540-8f66-4fe2-b8f2-526e7025ace7

### CODE REVIEW

**Comment by IlluminatiFish** [comment]
The references you provide in this rule seem to contain a few requests that make it seem that this is part of a wider Phishing-as-a-Service system. 

Note the files called `ResourceRedConfig.js` and `urlConfig.json`, these seem to be indicative of a broader PhaaS system in play here. Maybe it'd be best if we made a new rule detecting these?

https://urlscan.io/search/#filename%3A%22urlConfig.json%22%20AND%20filename%3A%22ResourceRedConfig.js%22

**Comment by masaomi346** [comment]
Re-created rules.

**Comment by IlluminatiFish** [comment]
Per articles found by searching the internet for the distinct file names, this seems to be a phishing kit developed by a threat actor dubbed 'Chenlun' by [DomainTools](https://www.domaintools.com/resources/blog/merry-phishmas-beware-us-postal-service-phishing-during-the-holidays/) and 'Sinkinto01' by [g0njxa](https://g0njxa.medium.com/chenlun-a-worldwide-phishing-carding-campaigns-provider-a45c4fed6d1b).

I think renaming the rule to `Chenlun Phishing Kit 88426540` would provide a more descriptive name.
Additionally I think that instead of using just `urlConfig.json`, we detect the path of the request using 
something along the lines of:

```yaml
urlConfig:
  requests|endswith: '/ResourceConfig/urlConfig.json'
```

**Review by IlluminatiFish — APPROVED** [review]
LGTM, I will wait for you to also approve the rule, so that we are both happy with it.

**Comment by masaomi346** [comment]
I think this is fine.
Thank you very much.

**Pull request merged**
