### PR TITLE
Added four new rules and made a few updates

### PR DESCRIPTION
**Pull request by IlluminatiFish**
- Updated SettingsJS crypto drainer rule
- Renamed Asli crypto drainer rule name
- Added new ToastrJS crypto drainer rule
- Added two new BbyStealer dropped website rules
- Added new rusc crypto drainer rule

### CODE REVIEW

**Comment by actually-akac** [comment]
You should add a longer description for the BbyStealer Dropper rule as not everyone is familiar with the malware family.

**Comment by IlluminatiFish** [comment]
> You should add a longer description for the BbyStealer Dropper rule as not everyone is familiar with the malware family.

Added a brief description

**Review by actually-akac — CHANGES_REQUESTED** [review]
The title '**sc Crypto Drainer**' is unclear and the description _Detects a crypto drainer._ is insufficient.

**Comment by IlluminatiFish** [comment]
> Collaborator

The name has been updated to `rusc` `ru` meaning the language supported other than English and `sc` being the prefix of the cookie used within the drainer script

**Pull request merged**
